kafka:
  broker: streaming-service-public-kafka-bootstrap.streaming-public:9092
  strimziCluster: streaming-service-public
  storageSize: 100Gi
  defaultPartitions: 3
  defaultReplicas: 3
  topics:
  - name: smoke-test
  resources:
    requests:
      cpu: 100m
      memory: 3Gi
    limits:
      cpu: 1000m
      memory: 4Gi


tlsSidecar:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 128Mi
