kafka:
  version: 2.1.1
  broker: streaming-service-kafka-bootstrap.streaming-prime:9092
  strimziCluster: streaming-service
  storageSize: 100Gi
  defaultPartitions: 1
  defaultReplicas: 3
  topics:
    - name: smoke-test
    - name: dataset-registry
    - name: streaming-raw
    - name: streaming-transformed
    - name: streaming-persisted
    - name: streaming-dead-letters
    - name: event-stream
  resources:
    requests:
      cpu: 1400m
      memory: 12500M
    limits:
      cpu: 1400m
      memory: 12500M


tlsSidecar:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

tolerations:
  - key: scos.run.kafka
    operator: Equal
    value: "true"
    effect: NoExecute

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scos.run.kafka
              operator: In
              values:
                - "true"
