kafka:
  deploymentName: streaming-service
  storageSize: 100Gi
  topics:
  - name: smoke-test
    partitions: 3
    replicas: 2

tlsSidecar:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 128Mi
