kafka:
  broker: streaming-service-kafka-bootstrap.streaming-prime:9092
  strimziCluster: streaming-service
  storageSize: 100Gi
  defaultPartitions: 100
  defaultReplicas: 3
  topics:
  - name: smoke-test
  - name: dataset-registry
  - name: streaming-og
  - name: streaming-raw
  - name: streaming-validated
  - name: streaming-transformed
  - name: organization-raw
  - name: streaming-persisted
  - name: streaming-dead-letters
  resources:
    requests:
      cpu: 200m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 6Gi


tlsSidecar:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 128Mi
