kafka:
  strimziCluster: streaming-service
  storageSize: 100Gi
  defaultPartitions: 3
  defaultReplicas: 2
  topics:
  - name: smoke-test
  - name: dataset-registry
  - name: streaming-og
  - name: streaming-raw
  - name: streaming-validated
  - name: streaming-transformed

tlsSidecar:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 128Mi
