apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: streaming-service
spec:
  kafka:
    replicas: 5
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 5
      transaction.state.log.replication.factor: 5
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 2Gi
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
  zookeeper:
    replicas: 5
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
