apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: streaming-service
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      requests:
        cpu: "1000m"
        memory: 2Gi
      limits:
        cpu: "1000m"
        memory: 2Gi
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    rack:
      topologyKey: failure-domain.beta.kubernetes.io/zone
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        cpu: "250m"
        memory: 256Mi
      limits:
        cpu: "250m"
        memory: 256Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}
    resources:
      requests:
        cpu: "250m"
        memory: 256Mi
      limits:
        cpu: "250m"
        memory: 256Mi
