apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-test
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: smoke-test-consumer
        image: ryane/kafkacat
        command: ["bash", "-c", "kafkacat -C -b {{ .Values.kafka.strimziCluster }}-kafka-bootstrap -t smoke-test -e"]
      - name: smoke-test-producer
        image: ryane/kafkacat
        command: ["bash", "-c", "echo 'foo' | kafkacat -P -b {{ .Values.kafka.strimziCluster }}-kafka-bootstrap -t smoke-test"]
      restartPolicy: OnFailure
