{{- range $topic := .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafka.deploymentName }}
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
{{- end }}
