apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
spec:
  limits:
  - default:
      memory: 128Mi
      cpu: 10m
    defaultRequest:
      memory: 128Mi
      cpu: 10m
    type: Container
