apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-test-topic 
  labels:
    strimzi.io/kind: topic
    strimzi.io/cluster: streaming-service
data:
  name: smoke-test-topic 
  partitions: "1"
  replicas: "3"
  config: "{}"