---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-smoke-tester
  labels:
    app: kafka-smoke-tester
spec:
  imagePullSecrets:
    - name: regcred
  restartPolicy: Never
  containers:
    - name: kafka-smoke-tester
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/streaming-service-smoke-test:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: smoke-test-topic
  initContainers:
    - name: wait-for-kafka
      image: busybox
      envFrom:
        - configMapRef:
            name: smoke-test-topic
      command:
        - sh
        - -c
        - |
          until echo dump | nc streaming-service-zookeeper 2181 | grep brokers | wc -l | grep -x "${replicas}"; do sleep 1; done
